/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/component/layout/Footer.vue')['default']
    Header: typeof import('./src/component/layout/Header.vue')['default']
    HomeContent: typeof import('./src/component/area/homepage/HomeContent.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
