/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/pages/AboutPage.vue')['default']
    ArchivePage: typeof import('./src/pages/ArchivePage.vue')['default']
    ContentPageLayout: typeof import('./src/component/common/ContentPageLayout.vue')['default']
    Footer: typeof import('./src/component/layout/Footer.vue')['default']
    GlassCard: typeof import('./src/component/common/GlassCard.vue')['default']
    Header: typeof import('./src/component/layout/Header.vue')['default']
    HomeContent: typeof import('./src/component/area/homepage/HomeContent.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    MarkdownContent: typeof import('./src/component/common/MarkdownContent.vue')['default']
    PostDetailPage: typeof import('./src/pages/PostDetailPage.vue')['default']
    PostFolderTree: typeof import('./src/component/content/PostFolderTree.vue')['default']
    PostsPage: typeof import('./src/pages/PostsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsPage: typeof import('./src/pages/TagsPage.vue')['default']
  }
}
